//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashierElvira
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detailtransaksi
    {
        public int iddetailtransaksi { get; set; }
        public string kodetransaksi { get; set; }
        public string kodeproduk { get; set; }
        public string namaproduk { get; set; }
        public decimal hargadijual { get; set; }
        public decimal jumlahproduk { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual tbl_produk tbl_produk { get; set; }
        public virtual tbl_transaksi tbl_transaksi { get; set; }
    }
}
