//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashierElvira
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pelanggan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_pelanggan()
        {
            this.tbl_transaksi = new HashSet<tbl_transaksi>();
        }
    
        public string kodepelanggan { get; set; }
        public string namapelanggan { get; set; }
        public string nohppelanggan { get; set; }
        public string alamatpelanggan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_transaksi> tbl_transaksi { get; set; }
    }
}
