//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Ras_Komputer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_raskomputerEntities : DbContext
    {
        public db_raskomputerEntities()
            : base("name=db_raskomputerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_detailtransaksi> tbl_detailtransaksi { get; set; }
        public virtual DbSet<tbl_produk> tbl_produk { get; set; }
        public virtual DbSet<tbl_transaksi> tbl_transaksi { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
