//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Ras_Komputer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public string kodeuser { get; set; }
        public string namauser { get; set; }
        public string passworduser { get; set; }
        public string leveluser { get; set; }
    }
}
