//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Ras_Komputer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_produk
    {
        public string kodeproduk { get; set; }
        public string namaproduk { get; set; }
        public decimal hargaproduk { get; set; }
        public decimal jumlahproduk { get; set; }
        public string satuanproduk { get; set; }
    }
}
