//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Ras_Komputer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transaksi
    {
        public string kodetransaksi { get; set; }
        public System.DateTime tanggal { get; set; }
        public string namacustomer { get; set; }
        public decimal dibayar { get; set; }
        public decimal kembalian { get; set; }
    }
}
