//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Ras_Komputer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public string kodecustomer { get; set; }
        public string namacustomer { get; set; }
        public string alamatcustomer { get; set; }
        public string nohpcustomer { get; set; }
    }
}
