//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BukaKasir
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_transaksi()
        {
            this.tbl_detailtransaksi = new HashSet<tbl_detailtransaksi>();
        }
    
        public string kodetransaksi { get; set; }
        public System.DateTime tanggaltransaksi { get; set; }
        public System.TimeSpan jam { get; set; }
        public decimal total { get; set; }
        public string kodeuser { get; set; }
        public string kodepelanggan { get; set; }
        public decimal dibayar { get; set; }
        public decimal kembalian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detailtransaksi> tbl_detailtransaksi { get; set; }
        public virtual tbl_pelanggan tbl_pelanggan { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
