//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BukaKasir
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_produk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_produk()
        {
            this.tbl_detailtransaksi = new HashSet<tbl_detailtransaksi>();
        }
    
        public string kodeproduk { get; set; }
        public string namaproduk { get; set; }
        public decimal hargaproduk { get; set; }
        public string satuanproduk { get; set; }
        public decimal jumlahproduk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detailtransaksi> tbl_detailtransaksi { get; set; }
    }
}
